-- CREACION DE USUARIO CON PRIVILEGIOS SE HACER SOLO SELECT A TODAS TABLAS DE UNA BASE DE DATOS

CREATE USER usuario1 WITH PASSWORD 'password';
GRANT CONNECT ON DATABASE "Practice" TO usuario1; -- Indique la Base de Datos
GRANT USAGE ON SCHEMA public TO usuario1; -- Indique el SCHEMA
GRANT SELECT ON ALL TABLES IN SCHEMA public TO usuario1; -- Indique los comandos y SCHEMA
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO usuario1; 

-- CREACION DE USUARIO CON PRIVILEGIOS SE HACER SELECT, INSERT, UPDATE Y DELETE A TODAS LAS TABLAS DE UNA BASE DE DATOS
CREATE USER asistente1 WITH PASSWORD 'password';
GRANT CONNECT ON DATABASE "Practice" TO asistente1; -- Indique la Base de Datos
GRANT USAGE ON SCHEMA public TO asistente1; -- Indique el SCHEMA
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO asistente1; -- Indique los comandos y SCHEMA
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO asistente1;

